# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      dbnetwork:
        ipv4_address: ${DB_IPADDRESS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080